### ISSUE TITLE
Qwen Image Edit CLIP Loader (GGUF) error

### ISSUE THREAD

**Issue by thipokKub** [city96/ComfyUI-GGUF#317]
Refer to [this issue](https://github.com/comfyanonymous/ComfyUI/issues/9423)

**Comment by pheonis2** [comment]
+1 for this, Please update the repo @city96

**Comment by soldivelot** [comment]
same issue

**Comment by city96** [comment]
I've pushed the logic to get it to load, although I can't test it properly atm. https://github.com/city96/ComfyUI-GGUF/commit/0ca2aeb797d20b45e75ba25aa23d37a36954b9e6

I'd appreciate some feedback whether this works:

- Update ComfyUI-GGUF to latest.
- Download the [mmproj file from here](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) and place it in the same folder as your main Qwen2.5 VL text encoder gguf file.
- Rename it so it matches the main file. If your main file is `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf` then name it `Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf` (as long as the part before the quant name matches and it includes "mmproj" it should find it. Check console for errors if not.)
- Use the correct workflow. (i.e. needs a VAE encoder node + the `QwenImageEdit` text encoder node)

**Comment by thipokKub** [comment]
Confirm working

**Comment by pheonis2** [comment]
didnt work for me sadly.

**Comment by kevkid** [comment]
> I've pushed the logic to get it to load, although I can't test it properly atm. [0ca2aeb](https://github.com/city96/ComfyUI-GGUF/commit/0ca2aeb797d20b45e75ba25aa23d37a36954b9e6)
> 
> I'd appreciate some feedback whether this works:
> 
> * Update ComfyUI-GGUF to latest.
> * Download the [mmproj file from here](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) and place it in the same folder as your main Qwen2.5 VL text encoder gguf file.
> * Rename it so it matches the main file. If your main file is `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf` then name it `Qwen2.5-VL-7B-Instruct-UD-mmproj-F16.gguf` (as long as the part before the quant name matches and it includes "mmproj" it should find it. Check console for errors if not.)
> * Use the correct workflow. (i.e. needs a VAE encoder node + the `QwenImageEdit` text encoder node)

Tried this, only thing i am confused about is the vae encoder part? My workflow has one, but i cant seem to get past this error. I pulled latest master.

**Comment by thipokKub** [comment]
I am using the following files
- [`Qwen_Image_Edit-Q4_K_M.gguf`](https://huggingface.co/QuantStack/Qwen-Image-Edit-GGUF/resolve/main/Qwen_Image_Edit-Q4_K_M.gguf)
- [`Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf`](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf)
- [`Qwen2.5-VL-7B-Instruct-Q4_K_M-mmproj-F16.gguf`](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/mmproj-F16.gguf)
- [`qwen_image_vae.safetensors`](https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors)
- (Optional) [`Qwen-Image-Lightning-4steps-V1.0-bf16.safetensors`](https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-4steps-V1.0-bf16.safetensors)

I think there are some difference on the VAE on comfyui implementation, but I'm not sure where. So I just use the official comfy-org version

**Comment by fangcun010** [comment]
This setting works. 
- [Qwen_Image_Edit-Q4_K_M.gguf](https://huggingface.co/QuantStack/Qwen-Image-Edit-GGUF/resolve/main/Qwen_Image_Edit-Q4_K_M.gguf)

- [Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf)

- [Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/mmproj-F16.gguf)

- [qwen_image_vae.safetensors](https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors)

**Q4_K_M is not included**

<img width="894" height="482" alt="Image" src="https://github.com/user-attachments/assets/b555903a-c3ce-4606-a1c1-577107e24991" />

<img width="1898" height="624" alt="Image" src="https://github.com/user-attachments/assets/23bc06b3-0277-43f5-b2db-e4799ab2d4a4" />

**Comment by TheFlameWizard** [comment]
> I've pushed the logic to get it to load, although I can't test it properly atm. [0ca2aeb](https://github.com/city96/ComfyUI-GGUF/commit/0ca2aeb797d20b45e75ba25aa23d37a36954b9e6)
> 
> I'd appreciate some feedback whether this works:
> 
>     * Update ComfyUI-GGUF to latest.
> 
>     * Download the [mmproj file from here](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) and place it in the same folder as your main Qwen2.5 VL text encoder gguf file.
> 
>     * Rename it so it matches the main file. If your main file is `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf` then name it `Qwen2.5-VL-7B-Instruct-UD-mmproj-F16.gguf` (as long as the part before the quant name matches and it includes "mmproj" it should find it. Check console for errors if not.)
> 
>     * Use the correct workflow. (i.e. needs a VAE encoder node + the `QwenImageEdit` text encoder node)

The fix works

**Comment by kayselmecnun** [comment]
@city96  Thank you, It works for me, but naming the file manually is going to painful and cause duplications, considering Qwen Image Edit model would also require a different .mmproj file.

If possible, might be a good idea adding a third selection in the node, when Qwen models are selected in the type field.

**Comment by DestiZ** [comment]
i keep getting this error

TextEncodeQwenImageEdit
mat1 and mat2 shapes cannot be multiplied (5332x1280 and 3840x1280)

i cannot get this work are this correctly named

<img width="344" height="86" alt="Image" src="https://github.com/user-attachments/assets/02acde08-e11e-4df2-b166-af05b40ec49b" />

**Comment by Danamir** [comment]
> I've pushed the logic to get it to load, although I can't test it properly atm. [0ca2aeb](https://github.com/city96/ComfyUI-GGUF/commit/0ca2aeb797d20b45e75ba25aa23d37a36954b9e6)
> 
> I'd appreciate some feedback whether this works:
> 
>     * Update ComfyUI-GGUF to latest.
> 
>     * Download the [mmproj file from here](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) and place it in the same folder as your main Qwen2.5 VL text encoder gguf file.
> 
>     * Rename it so it matches the main file. If your main file is `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf` then name it `Qwen2.5-VL-7B-Instruct-UD-mmproj-F16.gguf` (as long as the part before the quant name matches and it includes "mmproj" it should find it. Check console for errors if not.)
> 
>     * Use the correct workflow. (i.e. needs a VAE encoder node + the `QwenImageEdit` text encoder node)

Working for me on Qwen Image Edit with `Qwen2.5-VL-7B-Instruct-Q6_K.gguf` and `Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf` .

**Comment by Cool-Phil** [comment]
> i keep getting this error
> 
> TextEncodeQwenImageEdit mat1 and mat2 shapes cannot be multiplied (5332x1280 and 3840x1280)
> 
> i cannot get this work are this correctly named
> 
> <img alt="Image" width="344" height="86" src="https://private-user-images.githubusercontent.com/15215159/479723994-02acde08-e11e-4df2-b166-af05b40ec49b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU2NDMxNzksIm5iZiI6MTc1NTY0Mjg3OSwicGF0aCI6Ii8xNTIxNTE1OS80Nzk3MjM5OTQtMDJhY2RlMDgtZTExZS00ZGYyLWIxNjYtYWYwNWI0MGVjNDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE5VDIyMzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZWQ2NTNiYmU0Mzk3Y2FkYzNlOTQ2MTdmY2UyZTUyMTY5M2Y3ZjAwN2E3MDA2OWQwOWU5MDU5MzAxMDAwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xj12vg9epknYh_9-QwPInfGRWdsgp39CjvAJVn00zPs">

You also need to update the loader.py file in ComfyUI-GGUF.

To do this update the "ComfyUI-GGUF" node via the ComfyUI Manager, as this fix has been merged into the main code

Or you can find the file in this directory:
custom_nodes/ComfyUI-GGUF/loader.py

And replace it with the version from this direct link to the specific commit that fixed the issue:
https://github.com/city96/ComfyUI-GGUF/commit/0ca2aeb797d20b45e75ba25aa23d37a36954b9e6

**Comment by city96** [comment]
@kayselmecnun 
>naming the file manually is going to painful and cause duplications, considering Qwen Image Edit model would also require a different .mmproj file.

You should only need one mmproj file per text encoder, it's not tied to the model (also, regular Qwen Image doesn't need it I don't think? only the edit one uses the visual part). If you have multiple quants of the same text encoder, it should still detect it if you name it the same as the filename without the quant at the end.

>If possible, might be a good idea adding a third selection in the node, when Qwen models are selected in the type field.

I was thinking of ways of solving that, the problem with adding another field is that it'd break existing workflows + it's not very future proof (what if we get a new model that uses two text encoder that both need mmproj files. Do we add a second field?)

You can't have a separate node just to load mmproj (well, you can, just not easily, because the model at that stage is already loaded).

**For now, I tried to improve the mmproj detection logic** (also edited the original message).

Naming it something like `Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf` should now work with everything, including `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf`, `Qwen2.5-VL-7B-Instruct-Q4_K_S.gguf` and all the others.

@DestiZ 
Sorry, the original detection logic was a bit iffy and didn't detect all names. If you update again it should work now even with the "Q8_K_XL" quant.

**Comment by soyv4** [comment]
> [@kayselmecnun](https://github.com/kayselmecnun)
> 
> > Присваивать имя файлу вручную будет утомительно и приведёт к дублированию, учитывая, что для модели Qwen Image Edit также потребуется другой файл .mmproj.
> 
> Вам понадобится только один файл mmproj на каждый текстовый кодировщик, он не привязан к модели (кстати, обычному Qwen Image он, кажется, не нужен? Визуальную часть использует только файл редактирования). Если у вас несколько квантов одного и того же текстового кодировщика, он всё равно должен его обнаружить, если вы назовёте его так же, как и файл, без кванта в конце.
> 
> > Если возможно, было бы хорошей идеей добавить третий выбор в узел, когда в поле типа выбраны модели Qwen.
> 
> Я думал о способах решения этой проблемы. Проблема с добавлением еще одного поля в том, что это нарушит существующие рабочие процессы, плюс это не очень перспективно в будущем (что, если у нас появится новая модель, использующая два текстовых кодировщика, которым обоим нужны файлы mmproj? Нужно ли нам добавлять второе поле?)
> 
> Невозможно иметь отдельный узел только для загрузки mmproj (точнее, можно, но это не так просто, поскольку модель на этом этапе уже загружена).
> 
> **На данный момент я попытался улучшить логику обнаружения mmproj** (также отредактировал исходное сообщение).
> 
> Если назвать его как-то так, `Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf`то теперь он будет работать со всем, включая `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf`, `Qwen2.5-VL-7B-Instruct-Q4_K_S.gguf`и со всеми остальными.
> 
> [@DestiZ](https://github.com/DestiZ) Извините, первоначальная логика распознавания была немного ненадежной и не определяла все имена. Если вы снова обновите, она должна работать даже с квантом "Q8_K_XL".

Updated the c repository, renamed my model from Qwen2.5-VL-7B-Instruct-Q5_K_M.gguf in Qwen2.5-VL-7B-Instruct-mmaview-F16.gguf and does not work, what should I do to make it work ?

**Comment by makisekurisu-jp** [comment]
> [@kayselmecnun](https://github.com/kayselmecnun)
> 
> > naming the file manually is going to painful and cause duplications, considering Qwen Image Edit model would also require a different .mmproj file.
> 
> You should only need one mmproj file per text encoder, it's not tied to the model (also, regular Qwen Image doesn't need it I don't think? only the edit one uses the visual part). If you have multiple quants of the same text encoder, it should still detect it if you name it the same as the filename without the quant at the end.
> 
> > If possible, might be a good idea adding a third selection in the node, when Qwen models are selected in the type field.
> 
> I was thinking of ways of solving that, the problem with adding another field is that it'd break existing workflows + it's not very future proof (what if we get a new model that uses two text encoder that both need mmproj files. Do we add a second field?)
> 
> You can't have a separate node just to load mmproj (well, you can, just not easily, because the model at that stage is already loaded).
> 
> **For now, I tried to improve the mmproj detection logic** (also edited the original message).
> 
> Naming it something like `Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf` should now work with everything, including `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf`, `Qwen2.5-VL-7B-Instruct-Q4_K_S.gguf` and all the others.
> 
> [@DestiZ](https://github.com/DestiZ) Sorry, the original detection logic was a bit iffy and didn't detect all names. If you update again it should work now even with the "Q8_K_XL" quant.

Following the recent update, the problem remains unresolved.

<img width="1920" height="998" alt="Image" src="https://github.com/user-attachments/assets/5ddb672e-a9e4-490b-a26c-a5d7b3dfa181" />

**Comment by SunixLiu** [comment]
> I've pushed the logic to get it to load, although I can't test it properly atm. [0ca2aeb](https://github.com/city96/ComfyUI-GGUF/commit/0ca2aeb797d20b45e75ba25aa23d37a36954b9e6)
> 
> I'd appreciate some feedback whether this works:
> 
> * Update ComfyUI-GGUF to latest.
> * Download the [mmproj file from here](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) and place it in the same folder as your main Qwen2.5 VL text encoder gguf file.
> * Rename it so it matches the main file. If your main file is `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf` then name it `Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf` (as long as the part before the quant name matches and it includes "mmproj" it should find it. Check console for errors if not.)
> * Use the correct workflow. (i.e. needs a VAE encoder node + the `QwenImageEdit` text encoder node)

Working for me on Qwen_Image_Edit-Q4_K_M.gguf with Qwen2.5-VL-7B-Instruct-Q6_K.gguf and Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf

**Comment by makisekurisu-jp** [comment]
It turns out that both Qwen2.5-VL-7B-Instruct-Q6_K.gguf and Qwen2.5-VL-7B-Instruct-mmproj-BF16 must be manually downloaded and saved to the ComfyUI/models/text_encoders directory.

**Comment by tampadesignr** [comment]
updating code and now i get out of gpu memory
updating everything i had fixed it/// lol

**Comment by Lime81** [comment]
Working for me , uddate the node and rename the mmproj , Using mmproj 'Qwen2.5-VL-7B-Instruct-UD-Q8_K_XL-mmproj-F16.gguf' for text encoder 'Qwen2.5-VL-7B-Instruct-UD-Q8_K_XL.gguf'.

**Comment by shyt47** [comment]
Nope. not working for me. No matter what I try. Also I see in the drop down it has qwen_image as the type in that node but I do not have that when I select the drop down. Could this be my issue? Comfy is up to date.

**Comment by kevkid** [comment]
> Nope. not working for me. No matter what I try. Also I see in the drop down it has qwen_image as the type in that node but I do not have that when I select the drop down. Could this be my issue? Comfy is up to date.

Did you update the comfy gguf node?

**Comment by camoody1** [comment]
I'm probably just a lot dumber than everyone else here, but once I have both the gguf and mmproj files downloaded, renamed and placed in the same text_encoders folder, which of the two do I use in the Clip node? When I try to use the mmproj file, I get the mismatch error. What is the mmproj file supposed to do? I've never heard of this project or used it before.

**Comment by ialhabbal** [comment]
So, in the cliploader, do I select the "Qwen2.5-VL-7B-Instruct-mmproj-BF16" or the "Qwen2.5-VL-7B-Instruct-Q5_K_M"? This is bit confusing since the node only allows for one clip.

**Comment by camoody1** [comment]
> So, in the cliploader, do I select the "Qwen2.5-VL-7B-Instruct-mmproj-BF16" or the "Qwen2.5-VL-7B-Instruct-Q5_K_M"? This is bit confusing since the node only allows for one clip.

This is my same question.

**Comment by ialhabbal** [comment]
> > So, in the cliploader, do I select the "Qwen2.5-VL-7B-Instruct-mmproj-BF16" or the "Qwen2.5-VL-7B-Instruct-Q5_K_M"? This is bit confusing since the node only allows for one clip.
> 
> This is my same question.

When I used the Instruct model, I got a black image, and when I used the mmproj I got an error RuntimeError: mat1 and mat2 shapes cannot be multiplied (77x768 and 3072x768)

**Comment by makisekurisu-jp** [comment]
> I'm probably just a lot dumber than everyone else here, but once I have both the gguf and mmproj files downloaded, renamed and placed in the same text_encoders folder, which of the two do I use in the Clip node? When I try to use the mmproj file, I get the mismatch error. What is the mmproj file supposed to do? I've never heard of this project or used it before.
> 

https://openart.ai/workflows/rEMO6t2aKvvO8y1sv6Z8

**Comment by makisekurisu-jp** [comment]
Update the ComfyUI core and the ComfyUI GGUF node to the latest nightly version. If it still doesn’t work, manually install llama.cpp.

https://github.com/abetlen/llama-cpp-python

**Comment by ialhabbal** [comment]
With the latest update and renaming and everything, when I use the Instruct model, I got a black image, and when I used the mmproj I got an error RuntimeError: mat1 and mat2 shapes cannot be multiplied (77x768 and 3072x768), should these two clip models be used together? If so, how? If not, which one to use?

**Comment by armynew** [comment]
Update comfyui to lastest , gguf  des'not working

**Comment by Hermit6202** [comment]
> > i keep getting this error
> > TextEncodeQwenImageEdit mat1 and mat2 shapes cannot be multiplied (5332x1280 and 3840x1280)
> > i cannot get this work are this correctly named
> > <img alt="Image" width="344" height="86" src="https://private-user-images.githubusercontent.com/15215159/479723994-02acde08-e11e-4df2-b166-af05b40ec49b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU2NDMxNzksIm5iZiI6MTc1NTY0Mjg3OSwicGF0aCI6Ii8xNTIxNTE1OS80Nzk3MjM5OTQtMDJhY2RlMDgtZTExZS00ZGYyLWIxNjYtYWYwNWI0MGVjNDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE5VDIyMzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZWQ2NTNiYmU0Mzk3Y2FkYzNlOTQ2MTdmY2UyZTUyMTY5M2Y3ZjAwN2E3MDA2OWQwOWU5MDU5MzAxMDAwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xj12vg9epknYh_9-QwPInfGRWdsgp39CjvAJVn00zPs">
> 
> You also need to update the loader.py file in ComfyUI-GGUF.
> 
> To do this update the "ComfyUI-GGUF" node via the ComfyUI Manager, as this fix has been merged into the main code
> 
> Or you can find the file in this directory: custom_nodes/ComfyUI-GGUF/loader.py
> 
> And replace it with the version from this direct link to the specific commit that fixed the issue: [0ca2aeb](https://github.com/city96/ComfyUI-GGUF/commit/0ca2aeb797d20b45e75ba25aa23d37a36954b9e6)

Dit not work for me

**Comment by thipokKub** [comment]
> [@kayselmecnun](https://github.com/kayselmecnun)
> 
> > naming the file manually is going to painful and cause duplications, considering Qwen Image Edit model would also require a different .mmproj file.
> 
> You should only need one mmproj file per text encoder, it's not tied to the model (also, regular Qwen Image doesn't need it I don't think? only the edit one uses the visual part). If you have multiple quants of the same text encoder, it should still detect it if you name it the same as the filename without the quant at the end.
> 
> > If possible, might be a good idea adding a third selection in the node, when Qwen models are selected in the type field.
> 
> I was thinking of ways of solving that, the problem with adding another field is that it'd break existing workflows + it's not very future proof (what if we get a new model that uses two text encoder that both need mmproj files. Do we add a second field?)
> 
> You can't have a separate node just to load mmproj (well, you can, just not easily, because the model at that stage is already loaded).
> 
> **For now, I tried to improve the mmproj detection logic** (also edited the original message).
> 
> Naming it something like `Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf` should now work with everything, including `Qwen2.5-VL-7B-Instruct-UD-Q6_K_XL.gguf`, `Qwen2.5-VL-7B-Instruct-Q4_K_S.gguf` and all the others.
> 
> [@DestiZ](https://github.com/DestiZ) Sorry, the original detection logic was a bit iffy and didn't detect all names. If you update again it should work now even with the "Q8_K_XL" quant.

@city96 
Hello, maybe the new option can be hidden like for dynamic input? For example the following is a node that has `2` modes where `mode_2` will have `float_input` widget popup as needed

File structure
```
custom_nodes/example_dynamic_node
    |- __init__.py
    |- js
        |- dynamic_node.js
```

File `__init__.py`

```python
WEB_DIRECTORY = "./js"

class DynamicNode:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "mode": (["mode_1", "mode_2"],),
            },
            "optional": {
                "float_input": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 10.0}),
            },
        }

    RETURN_TYPES = ("STRING",)
    FUNCTION = "execute"
    CATEGORY = "Example"

    def execute(self, mode, **kwargs):
        if mode == "mode_1":
            return (str(-1.0),)
        
        elif mode == "mode_2":
            float_input = kwargs.get("float_input", 1.0)
            return (str(float_input ** 2),)

NODE_CLASS_MAPPINGS = {
    "DynamicNode": DynamicNode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "DynamicNode": "Dynamic Mode Node"
}
```

File `dynamic_node.js`

```javascript
import { app } from "../../scripts/app.js"

app.registerExtension({
	name: "MyDynamicNode.DynamicInputs.Final",
	async beforeRegisterNodeDef(nodeType, nodeData, app) {
		if (nodeData.name === "DynamicNode") {
			const onNodeCreated = nodeType.prototype.onNodeCreated;

			nodeType.prototype.onNodeCreated = function () {
				onNodeCreated?.apply(this, arguments);
				const node = this;

				const modeWidget = node.widgets.find((w) => w.name === "mode");

				const updateWidgets = (mode) => {
					const existingWidget = node.widgets.find((w) => w.name === "float_input");
					if (existingWidget) {
						node.widgets.splice(node.widgets.indexOf(existingWidget), 1);
					}

					if (mode === "mode_2") {
						const newWidget = node.addWidget(
							"number",      // type
							"float_input", // name (must match Python's kwargs)
							1.0,           // default value
							(value) => {
								// This callback is executed when the user changes the value.
								// The widget's value property is updated automatically by the core libs.
							},
							{ min: -10000, max: 10000, step: 0.01 } // options
						);
					}

					// Recalculate the node's size and force a redraw
					const newSize = node.computeSize();
					node.size = newSize;
					app.graph.setDirtyCanvas(true, true);
				};
				modeWidget.callback = (value) => {
					updateWidgets(value);
				};
				setTimeout(() => {
					updateWidgets(modeWidget.value);
				}, 1);
			};
		}
	},
});
```

**Example**

<img width="526" height="224" alt="Image" src="https://github.com/user-attachments/assets/6a98bac2-0fe4-4bb9-84e4-91dd0dcc75d7" />

<img width="529" height="235" alt="Image" src="https://github.com/user-attachments/assets/59b99337-55b9-4ee6-a317-7fc64988e0c5" />

---

The Load CLIP (GGUF) node can have the same structure as before, but if the option is `Qwen-Image-Edit` a new field will pop out to select the `mmproj` gguf file

See example PR https://github.com/city96/ComfyUI-GGUF/pull/318

**Comment by HaydenCupcake** [comment]
Thanks. This worked for me. Here is what I have in "D:\Stability Matrix\Data\Models\TextEncoders\Qwen\"
* Qwen2.5-VL-7B-Instruct-UD-Q8_0.gguf
* Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf

**Comment by Shyryp** [comment]
Full correct instruction:
1) Update ComfyUI to the latest version
2) Update ComfyUI-GGUF nodes to the "night" version
3) Download models:
[Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf)
[Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) (don't forget to rename the file to Qwen2.5-VL-7B-Instruct-mmproj-F16)
4) Place both of these models in the folder:
ComfyUI/models/text_encoders
5) If ComfyUI was running - restart it.
6) Refresh the page in the browser
7) Select the **Qwen2.5-VL-7B-Instruct-Q4_K_M**.gguf model in the **CLIPLoader (GGUF)** node with the "**qwen_image**" parameter. NOT mmproj-F16, only select Qwen2.5-VL-7B-Instruct-Q4_K_M in CLIPLoader (GGUF)!

This will automatically load Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf as a CLIP of the model "for Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf" - you will see this in the console.

Instead of Qwen2.5-VL-7B-Instruct-Q4_K_M there can be another Qwen2.5-VL-7B-Instruct.gguf (of a different quantization), the main thing is that it is in the text_encoders folder.

If you get a black image - it's probably something else - maybe the VAE is wrong, or there are problems with the llama-cpp libraries - try updating to the latest versions.

**Comment by everythingisc00l** [comment]
@Shyryp spasibo, finally - it's works!

**Comment by tampadesignr** [comment]
https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/tree/main
 Qwen2.5-VL-7B-Instruct-UD-Q8_K_XL.gguf
actually using this one : )

**Comment by Hermit6202** [comment]
> Full correct instruction:
> 
> 1. Update ComfyUI to the latest version
> 2. Update ComfyUI-GGUF nodes to the "night" version
> 3. Download models:
>    [Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf)
>    [Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) (don't forget to rename the file to Qwen2.5-VL-7B-Instruct-mmproj-F16)
> 4. Place both of these models in the folder:
>    ComfyUI/models/text_encoders
> 5. If ComfyUI was running - restart it.
> 6. Refresh the page in the browser
> 7. Select the **Qwen2.5-VL-7B-Instruct-Q4_K_M**.gguf model in the **CLIPLoader (GGUF)** node with the "**qwen_image**" parameter. NOT mmproj-F16, only select Qwen2.5-VL-7B-Instruct-Q4_K_M in CLIPLoader (GGUF)!
> 
> This will automatically load Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf as a CLIP of the model "for Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf" - you will see this in the console.
> 
> Instead of Qwen2.5-VL-7B-Instruct-Q4_K_M there can be another Qwen2.5-VL-7B-Instruct.gguf (of a different quantization), the main thing is that it is in the text_encoders folder.
> 
> If you get a black image - it's probably something else - maybe the VAE is wrong, or there are problems with the llama-cpp libraries - try updating to the latest versions.

For me it works only with the Q4_K_M versions

**Comment by KapperBear** [comment]
I just tested the instructions from @Shyryp and it worked with the Q6_K_XL version too. Thanks - some drive space is saved when I don't need to keep the safetensors CLIP file around!

**Comment by Vladskywolf** [comment]
> Full correct instruction:
> 
> 1. Update ComfyUI to the latest version
> 2. Update ComfyUI-GGUF nodes to the "night" version
> 3. Download models:
>    [Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf)
>    [Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf](https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/blob/main/mmproj-F16.gguf) (don't forget to rename the file to Qwen2.5-VL-7B-Instruct-mmproj-F16)
> 4. Place both of these models in the folder:
>    ComfyUI/models/text_encoders
> 5. If ComfyUI was running - restart it.
> 6. Refresh the page in the browser
> 7. Select the **Qwen2.5-VL-7B-Instruct-Q4_K_M**.gguf model in the **CLIPLoader (GGUF)** node with the "**qwen_image**" parameter. NOT mmproj-F16, only select Qwen2.5-VL-7B-Instruct-Q4_K_M in CLIPLoader (GGUF)!
> 
> This will automatically load Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf as a CLIP of the model "for Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf" - you will see this in the console.
> 
> Instead of Qwen2.5-VL-7B-Instruct-Q4_K_M there can be another Qwen2.5-VL-7B-Instruct.gguf (of a different quantization), the main thing is that it is in the text_encoders folder.
> 
> If you get a black image - it's probably something else - maybe the VAE is wrong, or there are problems with the llama-cpp libraries - try updating to the latest versions.

After frustratingly dealing with ComfyUI crashes using their recommended model 'qwen_image_edit_fp8_e4m3fn.safetensors' and failing to get the gguf model working on my own, I finally got everything to work following your instructions (and no black image).

Workflow nodes and loaded files (running with a 3090 w/24GB vram):

Unet Loader (GGUF): Qwen_Image_Edit-Q6_K.gguf
CLIPLoader (GGUF): Qwen2.5-VL-7B-Instruct-Q6_K.gguf
mmproj-F16.gguf renamed to Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf (in same folder as cliploader file - text_encode)
Load VAE: qwen_image_vae.safetensors

With an addititional Lora model in my workflow:
LoraLoaderModelOnly: Qwen-Image-Lightning-4steps-V1.0.safetensors

I bow before your beneficence, I can now stop pulling my hair out. Thank you kindly for this.

**Comment by trollver9000** [comment]
This works with Q4 , i have selected blue ones both names like this  

<img width="724" height="457" alt="Image" src="https://github.com/user-attachments/assets/d151e4be-1c98-4bbd-a1d3-4e6c8c688725" />
on the node you load just non mproj gguf which is Q4 
<img width="1057" height="398" alt="Image" src="https://github.com/user-attachments/assets/50bb6323-9a81-41bd-a4f7-e99e05ccbee4" />

All files here Q4 and mproj that has to be renamed  https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-GGUF/tree/main

This setup makes Whole Qwen image edit take up just about 8.8 GB VRAM, which is pretty amazing , so You dont have to use GGUF for UNET cause it works 2 times slower ! Instead use non gguf lightning version of Qwen.

<img width="524" height="210" alt="Image" src="https://github.com/user-attachments/assets/188f47db-af37-4e63-b121-86aa0ebc5f1a" />

**Comment by Ph0rk0z** [comment]
This works until the type metadata is set to mmproj instead of clip-vision. It cries about unknown architecture "clip". Sadly most *other* qwen-vl models that got quantized set the name to that and I'm having to get handy with the GUI editor.

What happens if you want to use the q8_0 mmproj? Did anyone try it and is the loading tied to the mmproj-F16.gguf filename?

**Comment by samuelchristlie** [comment]
I "solved" the unexpected architecture error with [#349](https://github.com/city96/ComfyUI-GGUF/pull/349). Allows me to load and run it as CLIP for Qwen Image Edit,

**Comment by Cloudreadypc** [comment]
mmproj file works with Q8 gguf text encoder (or less) but cannot be found when using bf16 gguf encoder even if the naming of mmproj file is correct.
