### ISSUE TITLE
Use t5_v1.1-xxl GGUF waste double times than t5xxl_fp8_e4m3fn in ClipTextEncoder

### ISSUE THREAD

**Issue by xueqing0622** [city96/ComfyUI-GGUF#83]
Use t5_v1.1-xxl GGUF waste double times than t5xxl_fp8_e4m3fn in ClipTextEncoder
t5xxl_fp8_e4m3fn  8s
t5_v1.1-xxl GGUF  19s
3060 12G

**Comment by xueqing0622** [comment]
And easy to get error in ClipTextEncoder

**Comment by al-swaiti** [comment]
https://github.com/user-attachments/assets/a21073e6-4c3a-454b-87f7-16282a21aba5

i compare q8 with fp8 there's not that difference plus q8 has better quality , q-k-m and k versions at all need more process , if you prefer speed than quality go with normal gguf versions  instead of K versions

**Comment by xueqing0622** [comment]
> [al-swaiti](/al-swaiti)

thx for your answer!

**Comment by ViratX** [comment]
> output.mp4 
> i compare q8 with fp8 there's not that difference plus q8 has better quality , q-k-m and k versions at all need more process , if you prefer speed than quality go with normal gguf versions instead of K versions

For 12GB VRAM, would you recommend using the "t5xxl_fp16.safetensors" which 9.11GB ?
Since model swapping is going to take place either ways, and Load/Unload time for difference is very little. 
I mean if it can fit in the VRAM then that would give the best quality of all.

**Comment by wujohns** [comment]
I found that the DualClipLoader (GGUF) uses the CPU to run the clip process, which makes the overall speed unusually slow

**Comment by wujohns** [comment]
> I found that the DualClipLoader (GGUF) uses the CPU to run the clip process, which makes the overall speed unusually slow

even I use the --highvram to start the comfyui

**Comment by wujohns** [comment]
Not only at beginning, when running the t5 in cpu is very slow, I force it load to gpu, and it run much quicker(about 8s vs <0.1s)

**Comment by city96** [comment]
I can reproduce the CPU thing when I run it on my second GPU but haven't had the time to look into it, I'll try to on the weekend.

**Comment by city96** [comment]
It should be fixed If you update both ComfyUI and this custom node to the latest version.

**Comment by camoody1** [comment]
When trying to use T5 6_K gguf in the DualClopLoader(GGUF) tonight, it still runs EXCEPTIONALLY slowly. I have updated both Comfy and all custom nodes. The workflow runs fine with the full T5 fp16 using the standard DualClipLoader. But as soon as I switch over the the GGUF loader, it runs horribly.

**Comment by camoody1** [comment]
Following a suggestion mentioned in an earlier comment, I added a node to force the Clip to be run on the GPU. After adding this node, the workflow is running smoothly. So, it sounds like something still isn't working correctly. 🤷🏼
